openapi: 3.0.3
info:
  version: "1.0.0"
  title: "CAPEL API-B2B"
  description: "Microservicios para la gestión de datos relacionados con retailers y distribuidores"
  contact:
    name: "Vladimir Reyes La O"
    email: "vladimir.reyess@gmail.com"
paths:
  /api/v1/login:
        post:
            tags:
                - "autenticación, seguridad"
            summary: "Login y autenticación de usuarios. Creacción de token de accesos"
            description: "Realiza la autenticación de usuarios, la creación de tokens de acceso y su gestión"
            operationId: login
            parameters: 
              - in: query
                name: offset
                schema:
                  type: integer
                description: The number of items to skip before starting to collect the result set
              - in: query
                name: limit
                schema:
                  type: integer
                description: The numbers of items to return
            
            responses:
                '200':
                    description: "OK"
                    content:
                        application/json:
                            schema:
                              type: string
                '401':
                    description: "Nombre de usuario o contraseña incorrectos"
                    content:
                        application/json:
                            schema:
                                type: string
                                properties:
                                    message:
                                        type: string
                                        example: "Acces Failure"
  /api/v1/data:
    get:
      tags:
          - "query, data"
      summary: "Devuelve resultados enmarcados en un rango de fecha"
      description: "Devuelve resultados enmarcados en un rango de fecha"
      operationId: data
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
      responses:
         '200':
            description: "OK"
            content:
              application/json:
                schema:
                  type: string

