name: "Docker: backend Images"

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: fjvigil/api-capel

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        pull: true
        tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}
      env:
          DB_HOST: ""
          DB_PORT: ""
          DB_NAME: ""
          DB_USER: ""
          DB_PASS: ""