name: "Docker: backend Images"

on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: fjvigil/api-capel

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        pull: true
        tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}
      env:
          DB_HOST: ""
          DB_PORT: ""
          DB_NAME: ""
          DB_USER: ""
          DB_PASS: ""
  deploy_ssh:
    name: Deploy ssh
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        known_hosts: 'frank@frank-HP-ProBook-450-G8-Notebook-PC'
    
    - name: Adding Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    - name: SSH_ Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      env:
        WOELCOME: "localhost"
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 22
        username: ${{ secrets.SERVER_USERNAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        before_script: | 
          docker rm -f apicapel
          docker rmi -f fjvigil/api-capel
        after_script: |
          docker run -p 80:80 --name apicapel -d fjvigil/api-capel
          